### ISSUE TITLE
Error when updating dynu.nu records

### ISSUE THREAD

**Issue by mlan** [nickbabcock/dness#294]
First I want to thank you for implementing support for dynu #290. 😄 

I have detected an issue when the DDNS record is out of sync and needs updating. I see the following (real IP and domain has been altered below):

```sh
root@srv:~# dness -c /etc/dness/dness.conf
[INFO  dness] resolved address to 100.100.100.100 in 2ms
[ERROR dness] could not update example.com (dynu)
        caused by: expected zero errors, but received: badauth
[INFO  dness] processed all: (updated: 0, already current: 3, missing: 0) in 2ms
[ERROR dness] at least one update failed, so exiting with non-zero status code
```

It can be worth mentioning that, using the identical credentials updating works using ddclient.

**Comment by nickbabcock** [comment]
I know for my tests I use the password from the IP Update Password: https://www.dynu.com/en-US/ControlPanel/ManageCredentials and updates are successful. But I know that dynu accepts several forms of authentication, though I'd prefer to keep things simple. Like the request can omit the username if supplying the password as a query param. I'd rather not support that approach. 

Here is the config I test with:

```toml
[[domains]]
type = "dynu"
hostname = "test-dness.camdvr.org"
username = "nickbabcock"

# ip update password:
# https://www.dynu.com/en-US/ControlPanel/ManageCredentials
password = "MyIpUpdatePassword"

# The records to update.
# "@" = "test-dness.camdvr.org"
# "sub = "sub.test-dness.camdvr.org"
records = [ "@", "sub" ]
```
