### ISSUE TITLE
GoDaddy IPv6-Support

### ISSUE THREAD

**Issue by bdewoop** [nickbabcock/dness#386]
Hey there
is it planned to support the IPv6 checkup too?

**Comment by nickbabcock** [comment]
Yes it is planned though not actively being worked on at the moment. Here are the high level tasks:

- Determine the IP versions to lookup for WAN (as one could have an IPv6 only machine or a dual stack, where both IPv4 and IPv6 are needed)
  - Taking inspiration from [godns](https://github.com/TimothyYe/godns), we could introduce an `ip_types` property for each domain like:
  ```toml
  [[domains]]
  type = "cloudflare"
  token = "dec0de"
  zone = "example.com"
  records = [
      "n.example.com"
  ]
  ip_types = ["4", "6"]

  # The default:
  # ip_types = ["4"] 
  ```
  If we see any domains that have an `ip_type` of `4` then the WAN IPv4 is looked up on start. Same thing for IPv6.
  - Will need to add the code to get IPv6 from the current WAN IP providers (opendns and ipify).
- Go through list of DNS providers and ensure that they can accept AAAA records and update the code accordingly
